on: [push]
jobs:
  FailBuildIssueDemo:
    runs-on: ubuntu-latest
    steps:
      - name: build
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/basic_script.sh 
      
      - name: test
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/test_script.sh 
        id: test

      - name: upload
        run: bash ${GITHUB_WORKSPACE}/.github/scripts/basic_script.sh
        if: success() || steps.test.conclusion == 'failure'

      - name: Step To run on failure
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Issue created bcz of workflow fialure: ${{ github.run_id }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n due to failure in run: _${{ github.run_id }}_."
            }'
