name: functions check worfkflow
on: [pull_request]

jobs:
  general-function-checks:
    runs-on: ubuntu-latest
    steps:
      - name: print GitHub context
        run: echo "${{ toJson(github) }}"
  status-function-checks:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: print username
        run: echo ${GITHUB_ACTOR}
      - name: Failing step
        id: demo
        run: exit 1
      - name: print runner context
        if: failure()
        run: echo "${{ toJson(runner) }}"
      - name: print hello always
        if: always()
        run: echo hello
