name: GitHub Actions schedule event
run-name: User- ${{ github.actor }}, scheduled this job🚀

on:
  schedule:
    - cron: '45 * * * *'
    - cron: '7 * * * *'

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files in the repository
        run: |
          hostname
          pwd
          ls
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
