name: Slack Send workflow
on: 
  workflow_dispatch:
    inputs:
      text:
        type: string
        required: true
        description: 'Text data'
jobs:
  SlackSendMsg:
    name: SlackSendMsg Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout the code
        uses: actions/checkout@v3
      - name: build
        env:
          SLACK_URL: ${{ secrets.SLACK_URL }}
        run: |
          pwd
          ls -lrtR
          bash send_slack.sh -u "$SLACK_URL" -t ${{ github.event.inputs.text }}
